version: '3'

dotenv:
  - ".env"

tasks:
  default:
    cmd: task --list
    desc: "タスク一覧を出力"
  
  apigen:
    cmds:
      - wsl mv ./src/openapi/generated.d.ts ./src/openapi/pastgen/past-generated.d.ts
      - npx openapi-typescript ./openapi.yaml -o ./src/openapi/generated.d.ts
    desc: "openapiの仕様書に沿ったコードのひな形を自動出力(既存のファイルはpastgenに移動)"